<?php

namespace Minimal\CoreBundle\Repository;

/**
 * RoutingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutingRepository extends \Doctrine\ORM\EntityRepository
{
}
